export const ADD_CHAT = "CHATS::ADD_CHAT";
export const ADD_MESSAGE = "CHATS::ADD_MESSAGE";
export const SET_NOTIFICATION = "CHATS::SET_NOTIFICATION";
export const DELETE_MESSAGE = "CHATS::DELETE_MESSAGE";
export const DELETE_CHAT = "CHATS::DELETE_CHAT";
export const ADD_BOT_CONVERSATION = "CHATS::ADD_BOT_CONVERSATION";

export const GET_CHATS_REUQEST = "CHATS::GET_CHATS_REUQEST";
export const GET_CHATS_SUCCESS = "CHATS::GET_CHATS_SUCCESS";
export const GET_CHATS_FAILURE = "CHATS::GET_CHATS_FAILURE";
