export const ADD_CHAT = "CHATS::ADD_CHAT";
export const ADD_MESSAGE = "CHATS::ADD_MESSAGE";
export const SET_NOTIFICATION = "CHATS::SET_NOTIFICATION";
export const DELETE_MESSAGE = "CHATS::DELETE_MESSAGE";
export const DELETE_CHAT = "CHATS::DELETE_CHAT";